### ISSUE TITLE
[question]: 执行 `pnpm run build:app` 会编译失败，能请教下吗

### ISSUE THREAD

**Issue by alexcdever** [akai007/uni-app-vue3-template#1]
我是直接克隆本项目到我的一个用于开发的Ubuntu VM里，但发生了build失败。我又另外在我本地macOS上测试一遍，也是这样。请问你知道是什么原因吗？
Linux的日志:

```text
 uni-app-vue3-demo git:(master) ✗ pnpm run build:app
Debugger attached.

> uni-app-vue3-demo@1.0.0 build:app /home/alex/project/vue/uni-app-vue3-demo
> uni build -p app

Debugger attached.
编译器版本：3.4.5（vue3）
正在编译中...
build production {
  VITE_USER_NODE_ENV: 'production',
  VITE_ROOT_DIR: '/home/alex/project/vue/uni-app-vue3-demo'
}

当前应用未配置 appid，无法使用 uni 统计，详情参考：https://ask.dcloud.net.cn/article/36303

vite v2.9.5 building for production...
[plugin:uni:app-vue-pages-json] Cannot read properties of undefined (reading 'autoclose')
at pages-json-js:1:0
error during build:
TypeError: Cannot read properties of undefined (reading 'autoclose')
    at getSplashscreen (/home/alex/project/vue/uni-app-vue3-demo/node_modules/.pnpm/@dcloudio+uni-cli-shared@3.0.0-alpha-3040520220408002_vue@3.2.33/node_modules/@dcloudio/uni-cli-shared/dist/json/app/manifest/splashscreen.js:40:40)
    at normalizeAppUniConfig (/home/alex/project/vue/uni-app-vue3-demo/node_modules/.pnpm/@dcloudio+uni-cli-shared@3.0.0-alpha-3040520220408002_vue@3.2.33/node_modules/@dcloudio/uni-cli-shared/dist/json/app/pages/uniConfig.js:15:86)
    at normalizeAppConfigService (/home/alex/project/vue/uni-app-vue3-demo/node_modules/.pnpm/@dcloudio+uni-cli-shared@3.0.0-alpha-3040520220408002_vue@3.2.33/node_modules/@dcloudio/uni-cli-shared/dist/json/app/pages/index.js:20:63)
    at Object.transform (/home/alex/project/vue/uni-app-vue3-demo/node_modules/.pnpm/@dcloudio+uni-app-vite@3.0.0-alpha-3040520220408002_vite@2.9.5+vue@3.2.33/node_modules/@dcloudio/uni-app-vite/dist/vue/plugins/pagesJson.js:32:76)
    at /home/alex/project/vue/uni-app-vue3-demo/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/shared/rollup.js:22779:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Waiting for the debugger to disconnect...
 ELIFECYCLE  Command failed with exit code 1.
Waiting for the debugger to disconnect...

```

**Comment by akai007** [comment]
已解决，直接拉一下最新代码试试

**Comment by alexcdever** [comment]
ok了，谢谢
