### ISSUE TITLE
跑不起来，报错！

### ISSUE THREAD

**Issue by dodu2014** [akai007/uni-app-vue3-template#3]
E:\demo\uni-app-vue3-template\node_modules\postcss-selector-parser\dist\selectors\attribute.js:1

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (E:\demo\uni-app-vue3-template\node_modules\postcss-selector-parser\dist\parser.js:22:42)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uni-app-vue3-demo@1.0.0 dev:mp-weixin: `uni -p mp-weixin`
npm ERR! Exit status 1

**Comment by 742764146** [comment]
根本不行
